spring:
  application:
    name: Sge
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/sge
    username: user_sge
    password: user_sge
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    drop-first: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: projeto.formacaobsb@gmail.com
    password: user_formacao
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

application:
  email:
    endereco-remetente: projeto.formacaobsb@gmail.com
    nome-remetente: Natal_da_Familia_Cardoso


